apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: rathaiah/spring-petclinic-demo:7
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32000
  selector:
    app: spring-petclinic
