apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic:3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinic:3
  template:
    metadata:
      labels:
        app: spring-petclinic:3
    spec:
      containers:
      - name: spring-petclinic:3
        image: rathaiah/spring-petclinic:3
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic:3
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32000
  selector:
    app: spring-petclinic:3
